import { StyleSheet } from 'react-native';
import { buttonSize, colors, dialog, interactionOpacity, layers, radius, spacing, typography } from '../../theme';

export const styles = StyleSheet.create({
  screenWrap: {
    flex: 1,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: layers.overlay,
    elevation: layers.overlay,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: spacing.md,
    gap: spacing.sm,
    paddingBottom: spacing.xl * 2,
  },
  createContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  createContent: {
    paddingBottom: spacing.xl * 2,
  },
  createBreadcrumbWrap: {
    borderBottomWidth: 1,
    borderBottomColor: colors.gray2,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  createBody: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    gap: spacing.md,
  },
  sectionTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  createButton: {
    backgroundColor: colors.primary1,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
  },
  createButtonText: {
    ...typography.body1_2,
    color: colors.white,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colors.white,
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    ...typography.body1_3,
    color: colors.gray6,
  },
  searchPlaceholderText: {
    color: colors.gray3,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    zIndex: layers.dropdown,
  },
  outputFilterWrap: {
    position: 'relative',
    zIndex: layers.overlay,
  },
  outputFilterButton: {
    minWidth: 74,
    height: buttonSize.chip,
    paddingHorizontal: spacing.xs,
    borderRadius: radius.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    backgroundColor: colors.background,
  },
  outputFilterText: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  outputFilterMenu: {
    position: 'absolute',
    top: 32,
    left: 0,
    minWidth: 104,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  outputFilterItem: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray1,
  },
  outputFilterItemSelected: {
    backgroundColor: colors.subbrown4,
  },
  outputFilterItemText: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  outputFilterItemTextSelected: {
    color: colors.primary1,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  filterText: {
    ...typography.body1_3,
  },
  filterTextActive: {
    color: colors.primary1,
  },
  filterTextInactive: {
    color: colors.gray5,
  },
  groupList: {
    gap: spacing.sm,
  },
  applyModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.48)',
    justifyContent: 'center',
    padding: spacing.md,
  },
  applyModalKeyboardWrap: {
    width: '100%',
    alignItems: 'center',
  },
  applyModalCard: {
    width: '100%',
    maxWidth: 520,
    minHeight: '56%',
    maxHeight: '92%',
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  applyModalScroll: {
    flex: 1,
  },
  applyModalContent: {
    gap: spacing.sm,
  },
  applyModalForm: {
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  applyModalInput: {
    height: 120,
    maxHeight: 144,
    borderRadius: radius.md,
    backgroundColor: colors.gray1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...typography.body1_3,
    color: colors.gray6,
  },
  applyModalCounterText: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'right',
  },
  applyModalActionRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: spacing.xs,
    paddingBottom: spacing.xs,
  },
  applyModalSubmitButton: {
    flex: 1,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.primary1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyModalSubmitDisabled: {
    backgroundColor: colors.gray2,
  },
  applyModalSubmitText: {
    ...typography.body1_2,
    color: colors.white,
  },
  applyModalCloseButton: {
    flex: 1,
    height: 40,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown2,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyModalCloseText: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  emptySearchBox: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    borderRadius: radius.md,
    paddingVertical: spacing.lg,
    alignItems: 'center',
  },
  emptySearchText: {
    ...typography.body1_3,
    color: colors.gray4,
  },
  groupCard: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    padding: spacing.md,
    gap: spacing.xs,
  },
  groupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  groupName: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  privateBadge: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xxs,
  },
  tag: {
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs - 2,
  },
  tagAmber: {
    backgroundColor: '#EFB56D',
  },
  tagCoral: {
    backgroundColor: '#E98F83',
  },
  tagSky: {
    backgroundColor: '#77C4E7',
  },
  tagViolet: {
    backgroundColor: '#8C77E8',
  },
  tagText: {
    ...typography.body1_3,
    color: colors.white,
  },
  groupMeta: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  groupActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  groupButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
  },
  outlineButton: {
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.white,
  },
  outlineButtonText: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  primaryButton: {
    backgroundColor: colors.primary1,
  },
  primaryButtonDisabled: {
    backgroundColor: colors.gray2,
  },
  primaryButtonText: {
    ...typography.body1_2,
    color: colors.white,
  },
  pressed: {
    opacity: interactionOpacity.pressed,
  },
  stepRow: {
    flexDirection: 'row',
    gap: spacing.xs + 2,
  },
  stepDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  stepDotActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.primary1,
  },
  stepDotDone: {
    borderColor: colors.subbrown2,
    backgroundColor: colors.subbrown2,
  },
  stepDotFuture: {
    borderColor: colors.gray2,
    backgroundColor: colors.white,
  },
  stepText: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  stepTextActive: {
    color: colors.white,
  },
  stepTextFuture: {
    color: colors.gray3,
  },
  sectionBox: {
    paddingTop: spacing.xs,
    gap: spacing.sm,
  },
  inlineRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'center',
  },
  inlineInput: {
    flex: 1,
  },
  helperText: {
    ...typography.caption1_3_relaxed,
    color: colors.gray4,
  },
  infiniteScrollLoadingText: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'center',
    paddingVertical: spacing.md,
  },
  textArea: {
    minHeight: 124,
    maxHeight: 180,
    paddingBottom: spacing.lg,
    textAlignVertical: 'top',
  },
  logoRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'stretch',
  },
  logoPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: radius.md,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.subbrown4,
  },
  createProfileCard: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.subbrown4,
    borderWidth: 1,
    borderColor: colors.subbrown3,
  },
  createProfilePreview: {
    width: 132,
    height: 148,
    borderRadius: radius.lg,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.subbrown3,
  },
  createProfilePreviewEmpty: {
    borderStyle: 'dashed',
    backgroundColor: '#FCF9F7',
  },
  createProfileEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    gap: spacing.xs,
  },
  createProfileCameraBadge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.subbrown4,
    borderWidth: 1,
    borderColor: colors.subbrown3,
  },
  createProfileEmptyTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  createProfileEmptyDescription: {
    ...typography.caption1_3,
    color: colors.gray4,
    textAlign: 'center',
  },
  createProfileActionColumn: {
    flex: 1,
    gap: spacing.xs,
  },
  createProfileActionButton: {
    minHeight: 62,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.subbrown3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  createProfileActionButtonSelected: {
    backgroundColor: colors.primary1,
    borderColor: colors.primary1,
  },
  createProfileActionButtonPrimary: {
    backgroundColor: colors.white,
    borderColor: colors.primary1,
  },
  createProfileActionButtonDisabled: {
    opacity: interactionOpacity.disabled,
  },
  createProfileActionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.subbrown4,
  },
  createProfileActionIconSelected: {
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  createProfileActionIconPrimary: {
    backgroundColor: colors.primary1,
  },
  createProfileActionTextWrap: {
    flex: 1,
    gap: 2,
  },
  createProfileActionTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  createProfileActionTitleSelected: {
    color: colors.white,
  },
  createProfileActionTitlePrimary: {
    color: colors.primary1,
  },
  createProfileActionDescription: {
    ...typography.caption1_3,
    color: colors.gray4,
  },
  createProfileActionDescriptionSelected: {
    color: 'rgba(255,255,255,0.86)',
  },
  createProfileActionDescriptionPrimary: {
    color: colors.gray5,
  },
  createProfilePreviewLarge: {
    width: '100%',
    height: 180,
    borderRadius: radius.lg,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.subbrown3,
  },
  createProfilePreviewLargeImage: {
    width: '100%',
    height: 180,
  },
  createProfileButtonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  createProfileBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown3,
    backgroundColor: colors.white,
  },
  createProfileBtnSelected: {
    backgroundColor: colors.primary1,
    borderColor: colors.primary1,
  },
  createProfileBtnPrimary: {
    borderColor: colors.primary1,
  },
  createProfileBtnText: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  createProfileBtnTextSelected: {
    color: colors.white,
  },
  createProfileBtnTextPrimary: {
    ...typography.body1_2,
    color: colors.primary1,
  },
  createProfileHint: {
    ...typography.caption1_3,
    color: colors.gray5,
  },
  checkboxRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'center',
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  checkBoxSquare: {
    width: 20,
    height: 20,
    borderRadius: radius.xs,
    borderWidth: 1,
    borderColor: colors.gray3,
  },
  checkBoxSquareActive: {
    backgroundColor: colors.primary1,
    borderColor: colors.primary1,
  },
  checkboxLabel: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  createVisibilityRow: {
    gap: spacing.sm,
  },
  createVisibilityCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown3,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  createVisibilityCardActive: {
    backgroundColor: colors.subbrown4,
    borderColor: colors.primary1,
  },
  createVisibilityIconWrap: {
    width: buttonSize.icon,
    height: buttonSize.icon,
    borderRadius: buttonSize.icon / 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3EAE4',
  },
  createVisibilityIconWrapActive: {
    backgroundColor: colors.primary1,
  },
  createVisibilityTextWrap: {
    flex: 1,
    gap: 2,
  },
  createVisibilityTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  createVisibilityTitleActive: {
    color: colors.primary1,
  },
  createVisibilityDescription: {
    ...typography.caption1_3,
    color: colors.gray4,
  },
  createVisibilityDescriptionActive: {
    color: colors.gray5,
  },
  addLinkButton: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  addLinkText: {
    ...typography.subhead3,
    color: colors.gray5,
  },
  navRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  navRowSingle: {
    justifyContent: 'flex-end',
  },
  breadcrumbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  breadcrumbPress: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    alignSelf: 'flex-start',
  },
  breadcrumbText: {
    ...typography.body2_2,
    color: colors.gray4,
  },
  breadcrumbActive: {
    color: colors.gray6,
  },
  input: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...typography.body1_3,
    color: colors.gray6,
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.white,
  },
  chipActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  chipText: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  chipTextActive: {
    color: colors.primary1,
  },
  formGroup: {
    gap: spacing.xs,
  },
  dupCheckButton: {
    minWidth: 92,
    height: buttonSize.field,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  dupCheckButtonDisabled: {
    opacity: interactionOpacity.disabled,
  },
  dupCheckText: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  nameCheckText: {
    ...typography.body2_3,
    marginTop: spacing.xxs,
  },
  nameCheckSuccessText: {
    color: '#2FA66A',
  },
  nameCheckErrorText: {
    color: colors.likeRed,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.white,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
  },
  secondaryText: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  primaryText: {
    ...typography.body1_2,
    color: colors.white,
  },
  buttonFlex: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
  },
  buttonGrow: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
  },
  buttonSingle: {
    minWidth: 112,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
  },
  disabledText: {
    color: colors.gray4,
  },
  detailTitle: {
    ...typography.subhead4_1,
    color: colors.gray6,
  },
  groupHomeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  groupHomeTitle: {
    marginTop: spacing.xs,
    ...typography.subhead3,
  },
  pillNav: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  pillNavItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.white,
  },
  pillNavItemActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.primary1,
  },
  pillNavText: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  pillNavTextActive: {
    color: colors.white,
  },
  detailCard: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    padding: spacing.md,
    gap: spacing.md,
  },
  detailTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  bookshelfDetailMenuButton: {
    width: buttonSize.chip,
    height: buttonSize.chip,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
  },
  detailTitleActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  detailTitleManageLink: {
    paddingVertical: spacing.xxs,
  },
  detailTitleManageLinkText: {
    ...typography.body1_2,
    color: colors.primary1,
    textDecorationLine: 'underline',
  },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.subbrown4,
    borderRadius: radius.md,
    padding: spacing.sm,
  },
  noticeText: {
    ...typography.body1_3,
    color: colors.gray6,
    flex: 1,
  },
  detailMain: {
    gap: spacing.md,
  },
  detailImage: {
    width: '100%',
    aspectRatio: 1.25,
    borderRadius: radius.md,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  detailImagePreview: {
    width: '100%',
    height: '100%',
    borderRadius: radius.md,
  },
  detailImageUploaded: {
    backgroundColor: colors.subbrown4,
    borderWidth: 1,
    borderColor: colors.subbrown3,
  },
  detailImageLabel: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  clubDefaultProfileArtworkPreview: {
    width: 132,
    height: 148,
    borderRadius: radius.lg,
  },
  clubDefaultProfileArtworkLarge: {
    width: '100%',
    height: 180,
    borderRadius: radius.lg,
  },
  clubDefaultProfileArtworkDetail: {
    width: 148,
    height: 148,
    borderRadius: radius.lg,
  },
  detailInfo: {
    gap: spacing.xs,
  },
  metaBlock: {
    gap: spacing.xxs,
  },
  metaLabel: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  metaValue: {
    ...typography.body1_4,
    color: colors.gray6,
  },
  detailBody: {
    ...typography.body1_3_relaxed,
    color: colors.gray6,
  },
  detailButtons: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  detailButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
  },
  clubParticipantsSection: {
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  clubParticipantsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  clubParticipantsTitleBlock: {
    gap: 2,
    flex: 1,
  },
  clubParticipantsTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  clubParticipantsCount: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  clubParticipantsStateBox: {
    borderWidth: 1,
    borderColor: colors.subbrown4,
    borderRadius: radius.md,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  clubParticipantsStateText: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  clubParticipantsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  clubParticipantCard: {
    minHeight: 76,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  clubParticipantIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  clubParticipantAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  clubParticipantAvatarImage: {
    width: '100%',
    height: '100%',
  },
  clubParticipantTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  clubParticipantNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    minWidth: 0,
  },
  clubParticipantNickname: {
    ...typography.body1_2,
    color: colors.gray6,
    flexShrink: 1,
    minWidth: 0,
  },
  clubParticipantStaffBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    borderRadius: radius.lg,
    backgroundColor: colors.subbrown4,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
  },
  clubParticipantStaffBadgeText: {
    ...typography.body2_3,
    color: colors.primary3,
  },
  clubParticipantRole: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  clubParticipantFollowButton: {
    minWidth: 68,
    minHeight: 34,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.primary1,
    borderWidth: 1,
    borderColor: colors.primary1,
  },
  clubParticipantFollowButtonActive: {
    backgroundColor: colors.white,
    borderColor: colors.gray2,
  },
  clubParticipantFollowButtonDisabled: {
    opacity: 0.55,
  },
  clubParticipantFollowText: {
    ...typography.body2_2,
  },
  clubParticipantFollowTextInactive: {
    color: colors.white,
  },
  clubParticipantFollowTextActive: {
    color: colors.gray5,
  },
  managementOverlay: {
    flex: 1,
    backgroundColor: colors.overlay30,
    justifyContent: 'flex-end',
    paddingTop: spacing.md,
    paddingBottom: 0,
  },
  managementOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  managementOverlayBottom: {
    flex: 1,
    backgroundColor: colors.overlay30,
    justifyContent: 'flex-end',
    padding: spacing.md,
  },
  managementCenteredOverlay: {
    flex: 1,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  managementInlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  managementMenuSheet: {
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    gap: spacing.sm,
    maxHeight: '82%',
  },
  managementHandleArea: {
    alignSelf: 'stretch',
    alignItems: 'center',
    paddingVertical: 10,
    marginTop: -10,
    marginBottom: spacing.xs - 10,
  },
  managementHandle: {
    width: 44,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.gray2,
  },
  managementMenuTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  managementMenuCaption: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  managementMenuScroll: {
    flexGrow: 0,
  },
  managementMenuList: {
    gap: spacing.sm,
    paddingBottom: spacing.xs,
  },
  managementMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.gray1,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
  },
  managementMenuIcon: {
    width: buttonSize.icon,
    height: buttonSize.icon,
    borderRadius: buttonSize.icon / 2,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementMenuTextWrap: {
    flex: 1,
    gap: 2,
  },
  managementMenuItemTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  managementMenuItemDescription: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  managementScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  managementScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray1,
    backgroundColor: colors.white,
  },
  managementScreenTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  managementHeaderSpacer: {
    width: 24,
    height: 24,
  },
  managementScreenScroll: {
    flex: 1,
  },
  managementScreenContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl * 3,
  },
  managementSummaryCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.xs,
  },
  managementSummaryTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  managementSummaryDescription: {
    ...typography.caption1_3_relaxed,
    color: colors.gray4,
  },
  teamManageLoadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  teamManageTopBar: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    gap: spacing.xs,
  },
  teamManageBookTitle: {
    ...typography.subhead2,
    color: colors.gray6,
  },
  teamManageHint: {
    ...typography.caption1_3_relaxed,
    color: colors.gray4,
  },
  teamManageDropBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  teamManageDropChip: {
    minHeight: buttonSize.icon,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamManageDropChipActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  teamManageDropChipDragActive: {
    borderColor: colors.green,
    backgroundColor: colors.background,
  },
  teamManageDropChipText: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  teamManageAddButton: {
    width: buttonSize.icon,
    height: buttonSize.icon,
    borderWidth: 1,
    borderColor: colors.subbrown3,
    borderRadius: buttonSize.icon / 2,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamManageContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xl * 2,
  },
  teamManageCard: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.md,
  },
  teamManageCardDragActive: {
    borderColor: colors.green,
    backgroundColor: colors.background,
  },
  teamManageCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  teamManageCardTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  teamManageRemoveButton: {
    width: buttonSize.chip,
    height: buttonSize.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teamManageMemberList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  teamManageMemberChip: {
    minWidth: 112,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  teamManageMemberChipSelected: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  teamManageMemberChipDragging: {
    opacity: 0.35,
  },
  teamManageMemberAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  teamManageMemberAvatarImage: {
    width: '100%',
    height: '100%',
  },
  teamManageMemberName: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  teamManageEmptySlot: {
    width: '100%',
    minHeight: 84,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.gray2,
    borderRadius: radius.md,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background,
  },
  teamManageEmptySlotText: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  teamManageFooter: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.gray1,
    backgroundColor: colors.background,
    gap: spacing.xs,
  },
  teamManageFooterHint: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'center',
  },
  teamManageSaveButton: {
    height: buttonSize.cta,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    borderWidth: 1,
  },
  teamManageSaveButtonActive: {
    backgroundColor: colors.primary1,
    borderColor: colors.primary1,
    shadowColor: colors.primary1,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  teamManageSaveButtonDisabled: {
    backgroundColor: colors.gray1,
    borderColor: colors.gray2,
  },
  teamManageSaveButtonText: {
    ...typography.body1_2,
    color: colors.white,
  },
  teamManageSaveButtonTextDisabled: {
    color: colors.gray4,
  },
  teamManageDraggingGhost: {
    position: 'absolute',
    minWidth: 112,
    borderWidth: 1,
    borderColor: colors.primary1,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    shadowColor: colors.black,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  teamManageDraggingGhostText: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  managementCountBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.lg,
    backgroundColor: colors.subbrown4,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  managementCountBadgeText: {
    ...typography.body2_2,
    color: colors.primary1,
  },
  managementCardList: {
    gap: spacing.sm,
  },
  managementListCard: {
    borderWidth: 1,
    borderColor: colors.gray1,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.xs,
  },
  managementListCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  managementIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  managementAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },
  managementIdentityText: {
    gap: 2,
    flex: 1,
  },
  managementPrimaryText: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  managementSecondaryText: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  managementMetaText: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  managementActionRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  managementGhostButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
  },
  managementGhostButtonText: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  managementPrimarySmallButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.primary1,
  },
  managementPrimarySmallButtonText: {
    ...typography.body2_2,
    color: colors.white,
  },
  managementEmptyCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.gray1,
    paddingVertical: spacing.xl,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementEmptyText: {
    ...typography.body1_3,
    color: colors.gray4,
  },
  detailLoadStateCard: {
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.gray2,
    padding: spacing.md,
    backgroundColor: colors.white,
    alignItems: 'center',
    gap: spacing.sm,
  },
  detailLoadInlineState: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailLoadStateText: {
    ...typography.body1_3,
    color: colors.gray4,
    textAlign: 'center',
  },
  detailLoadRetryButton: {
    minHeight: 36,
    paddingHorizontal: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.subbrown3,
    backgroundColor: colors.subbrown4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  detailLoadRetryText: {
    ...typography.body2_2,
    color: colors.primary1,
  },
  managementRoleBadge: {
    borderRadius: radius.lg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  managementRoleBadgeOwner: {
    backgroundColor: '#FFF1D8',
  },
  managementRoleBadgeStaff: {
    backgroundColor: '#E2F0FF',
  },
  managementRoleBadgeMember: {
    backgroundColor: colors.subbrown4,
  },
  managementRoleBadgeText: {
    ...typography.body2_3,
    color: colors.gray6,
  },
  managementWideButton: {
    marginTop: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
  },
  managementWideButtonText: {
    ...typography.body2_2,
    color: colors.primary1,
  },
  managementEditSection: {
    gap: spacing.md,
  },
  managementEditImageUploaded: {
    backgroundColor: colors.subbrown4,
    borderWidth: 1,
    borderColor: colors.subbrown3,
  },
  managementEditImageLabel: {
    ...typography.body2_3,
    color: colors.gray5,
    textAlign: 'center',
  },
  managementEditImagePreview: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: radius.md,
  },
  managementContactLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  managementContactLinkInputs: {
    flex: 1,
    gap: spacing.xs,
  },
  managementContactLinkRemoveButton: {
    width: 44,
    height: 44,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementToggleRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  managementToggleChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingVertical: spacing.sm,
  },
  managementToggleChipActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  managementToggleChipText: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  managementToggleChipTextActive: {
    color: colors.primary1,
  },
  managementFooter: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.gray1,
    backgroundColor: colors.white,
  },
  managementFooterButton: {
    flex: 1,
    borderRadius: radius.md,
    minHeight: 52,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managementFooterButtonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  managementFooterDangerButton: {
    borderColor: colors.likeRed,
    backgroundColor: colors.white,
  },
  managementFooterDangerButtonDisabled: {
    borderColor: colors.gray2,
  },
  managementFooterDangerButtonText: {
    ...typography.body1_2,
    color: colors.likeRed,
    textAlign: 'center',
  },
  managementFooterPrimaryButtonText: {
    ...typography.body1_2,
    color: colors.white,
    textAlign: 'center',
  },
  managementMessageCard: {
    width: '100%',
    maxWidth: 528,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    gap: spacing.md,
  },
  managementMessageTitle: {
    ...typography.subhead2,
    color: colors.primary2,
  },
  managementMessageBody: {
    ...typography.body1_2_spacious,
    color: colors.gray5,
  },
  managementMessageScroll: {
    maxHeight: 360,
  },
  managementModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  managementModalTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  managementBottomSheet: {
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.xs,
  },
  managementBottomSheetTitle: {
    ...typography.subhead3,
    color: colors.gray6,
    marginBottom: spacing.xs,
  },
  managementBottomSheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray1,
  },
  managementBottomSheetItemText: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  managementJoinActionCard: {
    width: '100%',
    maxWidth: 260,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    gap: spacing.xs,
  },
  managementJoinActionTitle: {
    ...typography.subhead2,
    color: colors.primary2,
  },
  managementJoinActionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray1,
  },
  managementJoinActionItemDisabled: {
    opacity: interactionOpacity.disabled,
  },
  managementJoinActionItemLast: {
    borderBottomWidth: 0,
  },
  managementJoinActionItemText: {
    ...typography.body1_2,
    color: colors.gray5,
  },
  managementJoinActionItemTextDisabled: {
    color: colors.gray3,
  },
  managementRoleMenuOverlay: {
    flex: 1,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  managementRoleMenuCard: {
    width: '100%',
    maxWidth: 292,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    gap: spacing.xs,
  },
  managementRoleMenuTitle: {
    ...typography.subhead2,
    color: colors.primary2,
  },
  managementRoleMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray1,
  },
  managementRoleMenuItemDisabled: {
    opacity: 0.45,
  },
  managementRoleMenuItemLast: {
    borderBottomWidth: 0,
  },
  managementRoleMenuItemText: {
    ...typography.body1_2,
    color: colors.gray5,
  },
  managementRoleMenuItemTextDisabled: {
    color: colors.gray3,
  },
  noticeBoardCard: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    padding: spacing.md,
    gap: spacing.md,
  },
  noticeBoardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticeBoardTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  noticeBoardDescription: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  noticeList: {
    gap: spacing.sm,
  },
  noticeItemRow: {
    borderWidth: 1,
    borderColor: colors.subbrown4,
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    minHeight: 58,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  noticeItemPhotoCount: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    flexShrink: 0,
  },
  noticeTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    flexShrink: 0,
  },
  noticeTag: {
    height: buttonSize.chip,
    minWidth: 42,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeTagPin: {
    backgroundColor: colors.primary1,
    minWidth: 36,
    paddingHorizontal: spacing.xs,
  },
  noticeTagGeneral: {
    backgroundColor: colors.secondary1,
  },
  noticeTagVote: {
    backgroundColor: colors.secondary3,
  },
  noticeTagMeeting: {
    backgroundColor: colors.secondary2,
  },
  noticeTagText: {
    ...typography.body2_2,
    color: colors.white,
  },
  noticeItemTitle: {
    ...typography.body1_2,
    color: colors.gray6,
    flex: 1,
    textAlign: 'left',
  },
  noticeItemMetaText: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  noticePagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
  },
  noticePageArrow: {
    width: buttonSize.chip,
    height: buttonSize.chip,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.white,
  },
  noticePageArrowDisabled: {
    opacity: interactionOpacity.disabled,
  },
  noticePageButton: {
    width: buttonSize.chip,
    height: buttonSize.chip,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
  },
  noticePageButtonActive: {
    backgroundColor: colors.subbrown4,
  },
  noticePageText: {
    ...typography.body2_2,
    color: colors.gray4,
  },
  noticePageTextActive: {
    color: colors.primary1,
  },
  noticeDetailCard: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.subbrown4,
    padding: spacing.md,
    gap: spacing.md,
  },
  noticeDetailTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticeDetailCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  noticeDetailMenuButton: {
    width: buttonSize.chip,
    height: buttonSize.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeDetailDate: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  noticeDetailTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  noticeDetailBody: {
    ...typography.body1_3_relaxed,
    color: colors.gray6,
  },
  noticeDetailBodySkeleton: {
    gap: spacing.sm,
  },
  noticePollSection: {
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.md,
  },
  noticeAttachmentCard: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.sm,
  },
  noticeAttachmentTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  noticeComposerPollHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  noticeComposerPollEditNote: {
    ...typography.body2_3,
    color: colors.likeRed,
    flexShrink: 1,
  },
  noticeBookshelfCard: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  noticeBookshelfCover: {
    width: 72,
    height: 104,
    borderRadius: radius.sm,
    backgroundColor: colors.gray1,
  },
  noticeBookshelfInfo: {
    flex: 1,
    gap: spacing.xxs,
  },
  noticeBookshelfTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  noticeBookshelfAuthor: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  noticePollMetaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticePollSchedule: {
    flex: 1,
    gap: 2,
  },
  noticePollEndText: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  noticePollMetaRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  noticePollMetaPrivacy: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  noticePollMetaText: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  noticePhotoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  noticePhotoItem: {
    width: '30%',
    minWidth: 88,
    aspectRatio: 1,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.gray2,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
  },
  noticePhotoImage: {
    width: '100%',
    height: '100%',
    borderRadius: radius.md,
  },
  noticePhotoLabel: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  noticePollOptionList: {
    gap: spacing.xs,
  },
  noticePollOptionRow: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    minHeight: 42,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticePollOptionRowSelected: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  noticePollOptionRowDisabled: {
    opacity: interactionOpacity.disabled,
  },
  noticePollOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flex: 1,
  },
  noticePollOptionText: {
    ...typography.body2_2,
    color: colors.gray6,
    flex: 1,
  },
  noticePollOptionCount: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
  },
  noticePollOptionCountText: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  noticePollSubmitButton: {
    marginTop: spacing.xs,
    alignSelf: 'flex-end',
    minWidth: 96,
    borderRadius: radius.md,
    backgroundColor: colors.primary1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  noticePollSubmitButtonDisabled: {
    backgroundColor: colors.gray2,
  },
  noticePollSubmitText: {
    ...typography.body1_2,
    color: colors.white,
  },
  noticeDetailImageStrip: {
    height: 180,
    borderRadius: radius.md,
    backgroundColor: colors.gray1,
  },
  noticeDetailDivider: {
    height: 1,
    backgroundColor: colors.gray2,
  },
  noticeCommentSection: {
    gap: spacing.sm,
  },
  noticeCommentHeader: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  noticeCommentInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  noticeCommentInput: {
    flex: 1,
    minHeight: 48,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...typography.body1_3,
    color: colors.gray6,
    backgroundColor: colors.white,
  },
  noticeCommentSubmit: {
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  noticeCommentSubmitText: {
    ...typography.body1_2,
    color: colors.white,
  },
  noticeCommentList: {
    gap: spacing.sm,
  },
  noticeCommentItem: {
    flexDirection: 'row',
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray2,
    paddingBottom: spacing.sm,
  },
  noticeCommentAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeCommentAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  noticeCommentBody: {
    flex: 1,
    gap: spacing.xxs,
  },
  noticeCommentMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  noticeCommentAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  noticeCommentAuthor: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  noticeCommentAuthorBadge: {
    borderWidth: 1,
    borderColor: colors.subbrown3,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    backgroundColor: colors.subbrown4,
  },
  noticeCommentAuthorBadgeText: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  noticeCommentDate: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  noticeCommentMenuButton: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeCommentText: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  noticeComposerCard: {
    borderWidth: 1,
    borderColor: colors.subbrown4,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.md,
  },
  noticeComposerLabel: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  noticeComposerFieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticeComposerTitleInput: {
    minHeight: 96,
    paddingBottom: spacing.md,
    textAlignVertical: 'top',
  },
  noticeComposerTextArea: {
    minHeight: 180,
    paddingBottom: spacing.lg,
    textAlignVertical: 'top',
  },
  noticeComposerActionRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  noticeComposerPinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticeComposerToggle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingVertical: spacing.sm,
  },
  noticeComposerToggleActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  noticeComposerToggleText: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  noticeComposerToggleTextActive: {
    color: colors.primary1,
  },
  noticeComposerDisabled: {
    opacity: interactionOpacity.disabled,
  },
  noticeComposerPinButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  noticeComposerPinButtonActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  noticeComposerPinButtonText: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  noticeComposerPinButtonTextActive: {
    color: colors.primary1,
  },
  noticeComposerSection: {
    gap: spacing.sm,
  },
  noticeComposerSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  noticeComposerLinkButton: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.white,
  },
  noticeComposerLinkButtonText: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  noticeComposerPollOptionList: {
    gap: spacing.xs,
  },
  noticeComposerPollOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
  },
  noticeComposerPollOptionInput: {
    flex: 1,
    minHeight: 48,
    paddingLeft: spacing.md,
    paddingRight: spacing.xs,
    paddingVertical: spacing.sm,
    ...typography.body1_3,
    color: colors.gray6,
  },
  noticeComposerPollOptionRemove: {
    width: 42,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeComposerAddOptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.white,
  },
  noticeComposerAddOptionText: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  noticeComposerChoiceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing.xs,
  },
  noticeComposerExclusiveChoiceGroup: {
    flex: 1,
    minWidth: 192,
    minHeight: 44,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  noticeComposerExclusiveChoice: {
    flex: 1,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  noticeComposerExclusiveChoiceDivider: {
    borderLeftWidth: 1,
    borderLeftColor: colors.gray2,
  },
  noticeComposerExclusiveChoiceActive: {
    backgroundColor: colors.subbrown4,
  },
  noticeComposerChoiceChip: {
    minWidth: 92,
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeComposerChoiceChipActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  noticeComposerChoiceChipText: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  noticeComposerChoiceChipTextActive: {
    color: colors.primary1,
  },
  noticeComposerDateRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  noticeComposerDateField: {
    flex: 1,
    gap: spacing.xxs,
  },
  noticeComposerDateLabel: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  noticeComposerDateInput: {
    flex: 0,
    width: '100%',
    minHeight: 44,
  },
  noticeComposerPhotoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  noticeComposerPhotoItem: {
    width: '30%',
    minWidth: 88,
    aspectRatio: 1,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    position: 'relative',
  },
  noticeComposerPhotoImage: {
    width: '100%',
    height: '100%',
    borderRadius: radius.md,
  },
  noticeComposerPhotoRemove: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeComposerCounter: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'right',
  },
  noticeComposerFooter: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.gray1,
    backgroundColor: colors.white,
  },
  noticeComposerFooterButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
  },
  noticeComposerFooterButtonDisabled: {
    opacity: 0.5,
  },
  noticeBookSelectorInlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: layers.overlay,
    elevation: layers.overlay,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  noticeBookSelectorCard: {
    width: '100%',
    maxWidth: dialog.maxWidth,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.md,
    maxHeight: '70%',
  },
  noticeBookSelectorList: {
    gap: spacing.sm,
  },
  noticeBookSelectorItem: {
    width: 112,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  noticeBookSelectorItemActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  noticeBookSelectorCover: {
    width: '100%',
    aspectRatio: 0.72,
    borderRadius: radius.sm,
    backgroundColor: colors.gray1,
  },
  noticeBookSelectorTitle: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  noticeBookSelectorMeta: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  bookshelfBookSearchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  bookshelfBookSearchInput: {
    flex: 1,
    ...typography.body1_3,
    color: colors.gray6,
    paddingVertical: 0,
  },
  bookshelfBookSearchInputDescenderSafe: {
    paddingVertical: spacing.xxs,
  },
  bookshelfBookSearchGuide: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  bookshelfBookSearchScreen: {
    flex: 1,
  },
  bookshelfBookSearchScroll: {
    flex: 1,
  },
  bookshelfBookSearchList: {
    gap: spacing.sm,
    paddingBottom: spacing.xl,
  },
  bookshelfBookSearchItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.sm,
  },
  bookshelfBookSearchItemActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  bookshelfBookSearchCover: {
    width: 56,
    height: 80,
    borderRadius: radius.sm,
    backgroundColor: colors.gray1,
  },
  bookshelfBookSearchInfo: {
    flex: 1,
    gap: spacing.xxs,
  },
  bookshelfBookSearchTitle: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  bookshelfBookSearchMeta: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  bookshelfBookSearchEmpty: {
    ...typography.body1_3,
    color: colors.gray4,
    textAlign: 'center',
    paddingVertical: spacing.xl,
  },
  bookshelfBookSearchLoadingMore: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
  },
  bookshelfBookSearchEndText: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'center',
    paddingVertical: spacing.sm,
  },
  bookshelfCreateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfCreateSelectorDisabled: {
    backgroundColor: colors.gray1,
  },
  bookshelfCreateSelectorText: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  bookshelfCreateSelectorPlaceholder: {
    color: colors.gray4,
  },
  bookshelfDatePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookshelfDatePickerValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  bookshelfDatePickerIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfDatePickerText: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  bookshelfDatePickerPlaceholder: {
    color: colors.gray4,
  },
  bookshelfCalendarCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.md,
  },
  bookshelfCalendarMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  bookshelfCalendarMonthButton: {
    width: buttonSize.icon,
    height: buttonSize.icon,
    borderRadius: buttonSize.icon / 2,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfCalendarMonthText: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  bookshelfCalendarWeekRow: {
    flexDirection: 'row',
  },
  bookshelfCalendarWeekLabel: {
    flex: 1,
    textAlign: 'center',
    ...typography.body2_3,
    color: colors.gray4,
  },
  bookshelfCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: spacing.xs,
  },
  bookshelfCalendarDay: {
    width: '14.2857%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfCalendarDayInner: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfCalendarDayCurrentMonth: {
    backgroundColor: colors.white,
  },
  bookshelfCalendarDayOutside: {
    opacity: 0.35,
  },
  bookshelfCalendarDayToday: {
    borderWidth: 1,
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  bookshelfCalendarDaySelected: {
    backgroundColor: colors.primary1,
  },
  bookshelfCalendarDayLabel: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  bookshelfCalendarDayLabelOutside: {
    color: colors.gray3,
  },
  bookshelfCalendarDayLabelSelected: {
    color: colors.white,
  },
  bookshelfCalendarFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  bookshelfCalendarFooterHint: {
    ...typography.body2_3,
    color: colors.gray4,
    flex: 1,
  },
  bookshelfCalendarTodayButton: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  bookshelfCalendarTodayButtonText: {
    ...typography.body2_2,
    color: colors.primary1,
  },
  voteVotersModalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  voteVotersModalCard: {
    width: '100%',
    maxWidth: dialog.maxWidth,
    maxHeight: 320,
    backgroundColor: colors.white,
    borderRadius: dialog.borderRadius,
    borderWidth: 1,
    borderColor: colors.gray2,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  voteVotersModalTitle: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  voteVotersList: {
    gap: spacing.xs,
  },
  voteVotersRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xxs,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray1,
  },
  voteVotersAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voteVotersName: {
    ...typography.body2_3,
    color: colors.gray6,
  },
  voteVotersEmptyText: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'center',
    paddingVertical: spacing.sm,
  },
  photoViewerOverlay: {
    flex: 1,
    backgroundColor: 'black',
    justifyContent: 'center',
  },
  photoViewerHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: layers.sticky,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  photoViewerCounter: {
    ...typography.body1_2,
    color: colors.white,
  },
  photoViewerClose: {
    padding: spacing.xs,
  },
  photoViewerItem: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactModalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  contactModalCard: {
    width: '100%',
    maxWidth: dialog.maxWidth,
    minHeight: 220,
    borderRadius: dialog.borderRadius,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    gap: spacing.lg,
  },
  contactModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  contactModalTitle: {
    ...typography.subhead1,
    color: colors.gray6,
    flex: 1,
  },
  contactModalLinkList: {
    gap: spacing.md,
  },
  contactModalLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.xs,
  },
  contactModalLinkTextWrap: {
    flex: 1,
  },
  contactModalLinkLabel: {
    ...typography.subhead4_1,
    color: colors.gray6,
  },
  contactModalEmptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 96,
  },
  contactModalEmptyText: {
    ...typography.body1_3,
    color: colors.gray5,
    textAlign: 'center',
  },
  bookshelfSection: {
    gap: spacing.md,
  },
  bookshelfSessionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.xxs,
  },
  bookshelfSessionChip: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.sm,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  bookshelfSessionChipInactive: {
    borderColor: colors.gray2,
    backgroundColor: colors.white,
  },
  bookshelfSessionChipActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  bookshelfSessionText: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  bookshelfSessionTextActive: {
    color: colors.primary1,
  },
  bookshelfGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  bookshelfCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: colors.subbrown4,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  bookshelfCover: {
    width: '100%',
    aspectRatio: 0.72,
    borderRadius: radius.sm,
    backgroundColor: colors.gray1,
  },
  bookshelfTitle: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  bookshelfAuthor: {
    ...typography.body2_3,
    color: colors.gray5,
  },
  bookshelfBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xxs,
  },
  bookshelfSessionBadge: {
    borderRadius: radius.sm,
    backgroundColor: colors.subbrown1,
    paddingHorizontal: spacing.xs + 2,
    paddingVertical: 2,
  },
  bookshelfCategoryBadge: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing.xs + 2,
    paddingVertical: 2,
  },
  bookshelfCategoryPink: {
    backgroundColor: '#EAA8A0',
  },
  bookshelfCategoryBlue: {
    backgroundColor: colors.secondary3,
  },
  bookshelfCategoryPurple: {
    backgroundColor: colors.secondary4,
  },
  bookshelfCategoryOrange: {
    backgroundColor: colors.secondary2,
  },
  bookshelfCategoryTeal: {
    backgroundColor: '#79CFC1',
  },
  bookshelfBadgeText: {
    ...typography.body2_3,
    color: colors.white,
  },
  bookshelfLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  bookshelfLinkLabel: {
    ...typography.body2_3,
    color: colors.gray6,
  },
  bookshelfRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingTop: spacing.xxs,
  },
  bookshelfRatingText: {
    ...typography.body2_3,
    color: colors.gray5,
    marginLeft: spacing.xxs,
  },
  bookshelfDetailSection: {
    gap: spacing.md,
  },
  bookshelfDetailBookCard: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  bookshelfDetailBookCover: {
    width: 128,
    height: 192,
    borderRadius: radius.md,
    backgroundColor: colors.gray1,
  },
  bookshelfDetailBookInfo: {
    flex: 1,
    gap: spacing.xs,
  },
  bookshelfDetailBookTitle: {
    ...typography.subhead2,
    color: colors.gray6,
  },
  bookshelfDetailBookAuthor: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  bookshelfDetailBookDescription: {
    ...typography.caption1_3_loose,
    color: colors.gray5,
  },
  bookshelfDetailTabRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  bookshelfDetailTabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  bookshelfDetailTabButtonActive: {
    borderBottomColor: colors.primary1,
  },
  bookshelfDetailTabLabel: {
    ...typography.body1_3,
    color: colors.gray4,
  },
  bookshelfDetailTabLabelActive: {
    ...typography.body1,
    color: colors.primary1,
  },
  bookshelfPanel: {
    gap: spacing.sm,
  },
  bookshelfPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookshelfPanelTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  bookshelfPanelTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  bookshelfPanelAddButton: {
    width: buttonSize.icon,
    height: buttonSize.icon,
    borderWidth: 1,
    borderColor: colors.subbrown3,
    borderRadius: buttonSize.icon / 2,
    backgroundColor: colors.subbrown4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfComposerKeyboard: {
    flex: 1,
  },
  bookshelfComposerOverlay: {
    flex: 1,
    backgroundColor: colors.overlay30,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  bookshelfComposerCard: {
    width: '100%',
    maxWidth: dialog.maxWidth,
    borderRadius: dialog.borderRadius,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.md,
  },
  bookshelfComposerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  bookshelfComposerTitle: {
    ...typography.subhead2,
    color: colors.gray6,
  },
  bookshelfComposerLabel: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  bookshelfComposerInput: {
    minHeight: 140,
    maxHeight: 180,
    paddingBottom: spacing.lg,
  },
  bookshelfComposerCounter: {
    ...typography.body2_3,
    color: colors.gray4,
    textAlign: 'right',
    marginTop: spacing.xxs,
  },
  bookshelfComposerRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  bookshelfComposerRatingTrack: {
    minHeight: buttonSize.icon,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  bookshelfComposerRatingStarShell: {
    position: 'relative',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfComposerRatingValue: {
    ...typography.body2_2,
    color: colors.gray5,
    marginLeft: spacing.xs,
  },
  bookshelfComposerFooter: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  bookshelfPostList: {
    gap: spacing.sm,
  },
  bookshelfPostCard: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  bookshelfPostTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookshelfPostAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  bookshelfPostMenuButton: {
    width: buttonSize.chip,
    height: buttonSize.chip,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookshelfPostAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.gray1,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bookshelfPostAvatarImage: {
    width: '100%',
    height: '100%',
  },
  bookshelfPostAuthor: {
    ...typography.body1_2,
    color: colors.gray6,
  },
  bookshelfPostRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  bookshelfPostContent: {
    ...typography.body1_3_relaxed,
    color: colors.gray5,
  },
  bookshelfRegularSummaryCard: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.subbrown4,
    padding: spacing.md,
    gap: spacing.sm,
  },
  bookshelfRegularSummaryTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    paddingRight: spacing.xs,
  },
  bookshelfRegularSummaryTitleIconWrap: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  bookshelfRegularSummaryTitle: {
    ...typography.subhead4_1,
    color: colors.gray6,
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
  },
  bookshelfRegularSummaryMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  bookshelfRegularSummaryMetaText: {
    ...typography.body1_3,
    color: colors.gray5,
  },
  bookshelfGroupChipRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    paddingVertical: spacing.xxs,
  },
  bookshelfGroupChip: {
    minWidth: 68,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  bookshelfGroupChipActive: {
    borderColor: colors.primary1,
    backgroundColor: colors.subbrown4,
  },
  bookshelfGroupChipText: {
    ...typography.body2_2,
    color: colors.gray6,
  },
  bookshelfGroupChipTextActive: {
    color: colors.primary1,
  },
  bookshelfGroupSection: {
    gap: spacing.sm,
  },
  bookshelfRegularGroupPreviewCard: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.sm,
  },
  bookshelfRegularGroupPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookshelfRegularGroupPreviewLabel: {
    ...typography.body2_2,
    color: colors.gray4,
  },
  bookshelfRegularGroupMemberList: {
    gap: spacing.xs,
  },
  bookshelfRegularGroupMemberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  bookshelfRegularGroupMemberName: {
    ...typography.body1_3,
    color: colors.gray6,
  },
  bookshelfRegularGroupHint: {
    ...typography.body2_3,
    color: colors.gray4,
  },
  bookshelfGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookshelfGroupHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  bookshelfGroupTitle: {
    ...typography.subhead3,
    color: colors.gray6,
  },
  bookshelfGroupMemberWrap: {
    position: 'relative',
    zIndex: layers.raised,
  },
  bookshelfGroupMemberButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    paddingVertical: spacing.xxs,
  },
  bookshelfGroupMemberCount: {
    ...typography.body1_3,
    color: colors.gray4,
  },
  bookshelfGroupMemberDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    minWidth: 164,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.sm,
    gap: spacing.xs,
    shadowColor: colors.black,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  bookshelfGroupMemberDropdownTitle: {
    ...typography.body2_2,
    color: colors.gray5,
  },
  bookshelfGroupActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  bookshelfGroupActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    paddingVertical: spacing.xxs,
    paddingHorizontal: spacing.xs,
  },
  bookshelfGroupSortText: {
    ...typography.body1_3,
    color: colors.gray4,
  },
  bookshelfGroupPostList: {
    gap: spacing.sm,
  },
  bookshelfGroupPostCard: {
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    padding: spacing.md,
    gap: spacing.xs,
  },
  bookshelfGroupPostCardCompleted: {
    backgroundColor: '#E7F2E6',
    borderColor: '#D2E7CF',
    borderWidth: 2,
  },
  bookshelfGroupPostCardPending: {
    opacity: interactionOpacity.disabled,
  },
  teamManageSkeletonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  teamManageSkeletonAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  teamManageSkeletonName: {
    flex: 1,
    height: 14,
    borderRadius: 4,
  },
  noticeTabSkeletonWrap: {
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  noticeTabSkeletonCard: {
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
  },
  noticeTabSkeletonTitle: {
    height: 14,
    width: '70%',
    borderRadius: 4,
  },
  noticeTabSkeletonBody: {
    height: 12,
    width: '90%',
    borderRadius: 4,
  },
  noticeTabSkeletonDate: {
    height: 10,
    width: '40%',
    borderRadius: 4,
  },
  bookshelfSessionChipSkeleton: {
    width: 60,
    height: 32,
    borderRadius: radius.sm,
  },
  bookshelfTabSkeletonWrap: {
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  bookshelfTabSkeletonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: colors.gray2,
    borderRadius: radius.md,
  },
  bookshelfTabSkeletonThumb: {
    width: 48,
    height: 64,
    borderRadius: radius.xs,
  },
  bookshelfTabSkeletonInfo: {
    flex: 1,
    gap: spacing.xs,
  },
  bookshelfTabSkeletonTitle: {
    height: 14,
    width: '70%',
    borderRadius: 4,
  },
  bookshelfTabSkeletonSub: {
    height: 12,
    width: '50%',
    borderRadius: 4,
  },
});
