export const INPUT_LIMITS = {
  // 사용자 프로필
  NICKNAME: 20,
  USER_NAME: 10,
  USER_DESCRIPTION: 40,

  // 모임
  CLUB_NAME: 40,
  CLUB_DESCRIPTION: 500,
  CLUB_REGION: 40,
  CLUB_LINK_LABEL: 20,
  CLUB_LINK_URL: 100,
  CLUB_PROFILE_IMAGE_URL: 255,
  APPLY_REASON: 300,
  NOTICE_TITLE: 40,
  NOTICE_CONTENT: 1000,
  NOTICE_COMMENT: 300,
  NOTICE_POLL_OPTION: 255,
  NOTICE_POLL_OPTION_MAX: 6,
  NOTICE_IMAGE_COUNT: 5,

  // 콘텐츠
  BOOK_STORY_TITLE: 100,
  BOOK_STORY_CONTENT: 5000,
  BOOK_STORY_IMAGE_COUNT: 5,
  BOOK_STORY_COMMENT: 300,
  BOOK_STORY_COMMENT_IMAGE_COUNT: 5,
  NOTICE_COMMENT_IMAGE_COUNT: 5,
  BOOKSHELF_COMPOSER: 300,
  CHAT_MESSAGE: 400,
  REPORT_CONTENT: 500,
} as const;
