export const INPUT_LIMITS = {
  // 사용자 프로필
  NICKNAME: 20,
  USER_NAME: 10,
  USER_DESCRIPTION: 40,

  // 모임
  CLUB_NAME: 40,
  CLUB_DESCRIPTION: 500,
  CLUB_REGION: 40,
  CLUB_LINK_LABEL: 20,
  CLUB_LINK_URL: 100,
  APPLY_REASON: 300,
  NOTICE_TITLE: 50,
  NOTICE_CONTENT: 2000,
  NOTICE_POLL_OPTION_MAX: 6,

  // 콘텐츠
  BOOK_STORY_TITLE: 100,
  BOOK_STORY_CONTENT: 5000,
  BOOKSHELF_COMPOSER: 300,
  REPORT_CONTENT: 500,
} as const;
